### ISSUE TITLE
Alpha version checklist 

### ISSUE THREAD

**Issue by ohld** [fiztehradio/fiztehradio.github.io#5]
The list of basic functionality that should be implemented in Alpha versions. 

Radio functionality 
- [x] Play / Pause
- [x] Volume
- [x] Current track artist and title
- [x] Playlist 

Services integration
- [ ] Simple Yandex Metric copy-paste 
- [x] OneSignal push subscription 

Appearance 
- [ ] Background image (not just one solid color)
- [ ] Social links
- [ ] Mobile-friendly (at least play / pause functionality)

When all this features would be implemented, the Alpha version would be deployed.

Some things to be implemented in Beta version:
- [ ] Click trackers for Yandex Metric
- [ ] Better Mobile appearance
- [ ] About / Team / etc. pages
